name: CD - Deployment

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Frontend Docker image
        working-directory: ./front
        run: docker build -t antoinelm/bobapp-front:latest .

      - name: Save Frontend image
        run: docker save antoinelm/bobapp-front:latest -o /tmp/bobapp-front.tar

      - name: Upload Frontend image artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-image
          path: /tmp/bobapp-front.tar
          retention-days: 1

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Docker image
        working-directory: ./back
        run: docker build -t antoinelm/bobapp-back:latest .

      - name: Save Backend image
        run: docker save antoinelm/bobapp-back:latest -o /tmp/bobapp-back.tar

      - name: Upload Backend image artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-image
          path: /tmp/bobapp-back.tar
          retention-days: 1

  push-to-dockerhub:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download Frontend image artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-image
          path: /tmp

      - name: Download Backend image artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-image
          path: /tmp

      - name: Load Frontend image
        run: docker load -i /tmp/bobapp-front.tar

      - name: Load Backend image
        run: docker load -i /tmp/bobapp-back.tar

      - name: Push Frontend image to Docker Hub
        run: docker push antoinelm/bobapp-front:latest

      - name: Push Backend image to Docker Hub
        run: docker push antoinelm/bobapp-back:latest
